services:
  nodeapp:
    image: node:22.16.0
    container_name: nodeapp
    working_dir: /app
    volumes:
      - ./node:/app
    ports:
      - "80:3000"
    command: sh -c "npm install && npm start"


  mariadb:
    image: mariadb:11.0
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: iflovethenus
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.2
    container_name: phpmyadmin
    restart: always
    ports:
      - "81:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: iflovethenus

volumes:
  db_data:
